# Generated by Django 4.0.3 on 2022-04-10 02:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True)),
                ('mobile_code', models.CharField(max_length=3)),
                ('slug', models.CharField(choices=[('CH', 'Child'), ('SC', 'Schoolboy'), ('ST', 'Student'), ('WR', 'Worker'), ('RT', 'Retiree')], max_length=2)),
                ('time_zone', models.CharField(choices=[('MSK-1', 'Kaliningra'), ('MSK ', 'Moscow'), ('MSK+1', 'Samara'), ('MSK+2', 'Yekaterinburg'), ('MSK+3', 'Omsk'), ('MSK+4', 'Krasnoyarsk'), ('MSK+5', 'Irkutsk'), ('MSK+6', 'Yakutsk'), ('MSK+7', 'Vladivostok'), ('MSK+8', 'Srednekolymsk'), ('MSK+9', 'Kamchatka')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
                ('filter', models.CharField(max_length=3)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Waiting', 'Waiting'), ('Fail', 'Fail'), ('Error', 'Error')], max_length=10)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_client', to='main.client')),
                ('id_notification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_notifiacation', to='main.notification')),
            ],
        ),
    ]
