# Generated by Django 3.2.13 on 2022-04-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Waiting', 'Waiting'), ('No Sent', 'No Sent'), ('Error', 'Error'), ('Wrong Time', 'Wrong Time')], max_length=10),
        ),
    ]
